/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Pivotal tc Runtime 3.0.0.RELEASE/7.0.55.A.RELEASE
 * Generated at: 2014-08-29 19:32:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.controllers.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class configBlank_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/insight.tld", Long.valueOf(1404339226000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005finsight_005frenderPluginResources_0026_005farea_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005finsight_005frenderPluginResources_0026_005farea_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005finsight_005frenderPluginResources_0026_005farea_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t");
      if (_jspx_meth_insight_005frenderPluginResources_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_insight_005frenderPluginResources_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  insight:renderPluginResources
    com.springsource.insight.dashboard.util.RenderPluginResourcesTag _jspx_th_insight_005frenderPluginResources_005f0 = (com.springsource.insight.dashboard.util.RenderPluginResourcesTag) _005fjspx_005ftagPool_005finsight_005frenderPluginResources_0026_005farea_005fnobody.get(com.springsource.insight.dashboard.util.RenderPluginResourcesTag.class);
    _jspx_th_insight_005frenderPluginResources_005f0.setPageContext(_jspx_page_context);
    _jspx_th_insight_005frenderPluginResources_005f0.setParent(null);
    // /WEB-INF/controllers/home/configBlank.jsp(5,1) name = area type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_insight_005frenderPluginResources_005f0.setArea("CONFIG_BODY_SCRIPT");
    int[] _jspx_push_body_count_insight_005frenderPluginResources_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_insight_005frenderPluginResources_005f0 = _jspx_th_insight_005frenderPluginResources_005f0.doStartTag();
      if (_jspx_th_insight_005frenderPluginResources_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_insight_005frenderPluginResources_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_insight_005frenderPluginResources_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_insight_005frenderPluginResources_005f0.doFinally();
      _005fjspx_005ftagPool_005finsight_005frenderPluginResources_0026_005farea_005fnobody.reuse(_jspx_th_insight_005frenderPluginResources_005f0);
    }
    return false;
  }
}
